import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Toolbar from '../components/toolbar'
import styles from '../styles/Home.module.css'
import Draggable, { DraggableEventHandler } from 'react-draggable'
import { useState } from 'react'
type DraggableData = {
  node: HTMLElement,
  // lastX + deltaX === x
  x: number, y: number,
  deltaX: number, deltaY: number,
  lastX: number, lastY: number
};
const Home: NextPage = () => {
  const [dragCordinate,setDragCordiante] = useState({x:0,y:0})
  
  function resetDragItems(e : Event,position: DraggableData){
    console.log('drag stop')
    setDragCordiante({x:0,y:0});
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Toolbar/>
        <section className={styles.components}>
          <Draggable position={dragCordinate} onStop={resetDragItems as DraggableEventHandler}> 
            <div className={styles.unit}>
              <div className={styles.shape}/>
              <span className={styles.name}>Paragraph</span>
            </div>
          </Draggable>
          <Draggable position={dragCordinate} onStop={resetDragItems as DraggableEventHandler}> 
            <div className={styles.unit}>
              <div className={styles.shape}/>
              <span className={styles.name}>Button</span>
            </div>
          </Draggable>
        </section>
        <section className={styles.display}>
          <div className={styles.info}>
            <span>Mouse:11120323</span>
            <span>Dragging:11120323</span>
            <span>Instances: 3</span>
            <span>config:.................................................... ............................. .....................</span>
          </div>
          <div className={styles.structure}>
            <button>CCC</button>
          </div>
        </section>
        <section className={styles.config}>

        </section>
      </main>    
    </div>
  )
}

export default Home
