import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Toolbar from '../components/toolbar'
import styles from '../styles/Home.module.css'
import { DragEventHandler, MouseEventHandler, useRef, useState } from 'react'

const Home: NextPage = () => {
  const display = useRef(null)
  const [draggingElement, setDraggingElement] = useState('');
  const [mousePos,setMousePos] = useState({x:0,y:0});
  function dragStart(e: any){
    if((e.target as HTMLDivElement ).childNodes[1].textContent === 'Paragraph')
    setDraggingElement('ElementParagraph');
    else
    setDraggingElement('ElementButton');
  };
  function setRealtiveMousePos(e: any){
    let rect =  e.target.getBoundingClientRect();
    let x = Math.round(e.clientX  - rect.left);
    let y = Math.round(e.clientY - rect.top);
    if(x< 0) x= 0;
    if(y<0) y =0;
    setMousePos({x,y});
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Coding challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Toolbar/>

        <section className={styles.components} >
          <div className={styles.unit} onDragStart={dragStart} onDragEnd={()=>setDraggingElement('')} draggable={true}>
            <div className={styles.shape}/>
            <span className={styles.name}>Paragraph</span>
          </div>
          <div className={styles.unit} onDragStart={dragStart} onDragEnd={()=>setDraggingElement('')} draggable={true}>
            <div className={styles.shape}/>
            <span className={styles.name}>Button</span>
          </div>
        </section>

        <section className={styles.display} onMouseMove={setRealtiveMousePos} onMouseLeave={setRealtiveMousePos}>
          <div className={styles.info}>
            <span>Mouse:({`${mousePos.x},${mousePos.y}`}</span>
            <span>Dragging:{draggingElement}</span>
            <span>Instances: 3</span>
            <span>config:.................................................... ............................. .....................</span>
          </div>
          <div className={styles.structure} onDragOver={(e)=>{e.preventDefault()}} onDrop={(e)=> { e.preventDefault(); console.log(e)}}>
            <button>CCC</button>
          </div>
        </section>
        <section className={styles.config}>

        </section>
      </main>    
    </div>
  )
}

export default Home
